data_source main_db:
  type: postgres
  connection:
    host: ${POSTGRES_CONTAINER_NAME}
    port: ${POSTGRES_PORT}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
