# Use Node.js LTS version as base image
FROM node:18-alpine

# Define build argument
ARG MAIN_DATABASE_URL

# Set environment variable for build time
ENV MAIN_DATABASE_URL=postgresql://user:password@dataeng-postgres:5432/postgres_db

# Copy entrypoint script first
COPY scripts/next_entrypoint.sh /entrypoint.sh

# Set proper permissions
RUN chmod +x /entrypoint.sh

# Copy package files
COPY ./dashboard /app

WORKDIR /app

# Set entrypoint
ENTRYPOINT ["/entrypoint.sh"]

