FROM python:3.11-slim

USER root

COPY ./flask_endpoint/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY --chown=root:root ./flask_endpoint /app
COPY --chown=root:root ./flask_endpoint/app.py /app/app.py


WORKDIR /app

CMD ["python3", "app.py"]