services:
  scheduler:
    image: dataeng-dibimbing/airflow
    container_name: ${AIRFLOW_SCHEDULER_CONTAINER_NAME}
    hostname: ${AIRFLOW_SCHEDULER_CONTAINER_NAME}
    command: scheduler
    restart: always
    env_file:
      - ../.env
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_AIRFLOW_USER}:${POSTGRES_AIRFLOW_PASSWORD}@${POSTGRES_AIRFLOW_CONTAINER_NAME}/${POSTGRES_AIRFLOW_DB}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_CONTAINER_NAME=${POSTGRES_CONTAINER_NAME}
      - POSTGRES_ANALYSIS_CONTAINER_NAME=${POSTGRES_ANALYSIS_CONTAINER_NAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_ANALYSIS_PORT=${POSTGRES_ANALYSIS_PORT}
      - SPARK_MASTER_HOST_NAME=${SPARK_MASTER_HOST_NAME}
      - SPARK_MASTER_PORT=${SPARK_MASTER_PORT}
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../spark_scripts:/opt/airflow/spark_scripts
      - ../bash_scripts:/opt/airflow/bash_scripts
      - ../scripts:/scripts
      - ../data:/opt/airflow/data
      - ../jars:/opt/airflow/jars
  webserver:
    image: dataeng-dibimbing/airflow
    container_name: ${AIRFLOW_WEBSERVER_CONTAINER_NAME}
    hostname: ${AIRFLOW_WEBSERVER_CONTAINER_NAME}
    entrypoint: /scripts/entrypoint.sh
    restart: always
    depends_on:
      - scheduler
    env_file:
      - ../.env
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_AIRFLOW_USER}:${POSTGRES_AIRFLOW_PASSWORD}@${POSTGRES_AIRFLOW_CONTAINER_NAME}/${POSTGRES_AIRFLOW_DB}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_CONTAINER_NAME=${POSTGRES_CONTAINER_NAME}
      - POSTGRES_ANALYSIS_CONTAINER_NAME=${POSTGRES_ANALYSIS_CONTAINER_NAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_ANALYSIS_PORT=${POSTGRES_ANALYSIS_PORT}
      - SPARK_MASTER_HOST_NAME=${SPARK_MASTER_HOST_NAME}
      - SPARK_MASTER_PORT=${SPARK_MASTER_PORT}
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../spark_scripts:/opt/airflow/spark_scripts
      - ../bash_scripts:/opt/airflow/bash_scripts
      - ../scripts:/scripts
      - ../jars:/opt/airflow/jars
      - ../data:/opt/airflow/data
    ports:
      - ${AIRFLOW_WEBSERVER_PORT}:8080

networks:
  default:
    name: dataeng-network
    external: true
