services:
  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    container_name: kafka
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  dibimbing-dataeng-postgres:
    image: quay.io/debezium/example-postgres:${DEBEZIUM_VERSION}
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped
    hostname: ${POSTGRES_CONTAINER_NAME}
    networks:
      - dataeng-network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../sql:/sql
      - ../data:/data
    ports:
      - ${POSTGRES_PORT}:5432
    command: ["sh", "-c", "psql -f /sql/schema_ddl.sql"]

  dibimbing-dataeng-postgres-replica:
    image: quay.io/debezium/example-postgres:${DEBEZIUM_VERSION}
    container_name: ${POSTGRES_REPLICA_CONTAINER_NAME}
    restart: unless-stopped
    hostname: ${POSTGRES_REPLICA_CONTAINER_NAME}
    networks:
      - dataeng-network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_REPLICA_PASSWORD}
      - POSTGRES_USER=${POSTGRES_REPLICA_USER}
      - POSTGRES_DB=${POSTGRES_REPLICA_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../sql:/sql
      - ../data:/data
    ports:
      - ${POSTGRES_REPLICA_PORT}:5434
    command: ["sh", "-c", "psql -f /sql/schema_ddl.sql"]

  dibimbing-dataeng-postgres-analysis:
    image: quay.io/debezium/example-postgres:${DEBEZIUM_VERSION}
    container_name: ${POSTGRES_ANALYSIS_CONTAINER_NAME}
    restart: unless-stopped
    hostname: ${POSTGRES_ANALYSIS_CONTAINER_NAME}
    networks:
      - dataeng-network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ANALYSIS_PASSWORD}
      - POSTGRES_USER=${POSTGRES_ANALYSIS_USER}
      - POSTGRES_DB=${POSTGRES_ANALYSIS_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../sql:/sql
      - ../data:/data
    ports:
      - ${POSTGRES_PORT_ANALYSIS}:5433
    command: ["sh", "-c", "psql -f /sql/analysis_schema_ddl.sql"]

  connect:
    container_name: connect
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
      - 8083:8083
    depends_on:
      - kafka
      - mysql
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

networks:
  dataeng-network:
    driver: bridge
    external: true
